# Generated by Django 3.1.3 on 2020-11-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='fname')),
                ('gender', models.CharField(max_length=255, verbose_name='gender')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
            ],
        ),
    ]
